### PR TITLE
updating jokes on refresh icon click

### PR DESCRIPTION
**Pull request by nikhil3000**
Converted the call to get jokes in a function and started calling that function on click of the refresh icon. The API call to get jokes seems light, but we might not wanna do this if there is any limit on API call for jokes. 

Feel free to decline if this isn't a desired feature

### CODE REVIEW

**Comment by getnot** [comment]
I don't think these changes will stop new yo mama joke fetch on reload or new tab open.

this will just add a new way to fetch yo mama jokes when we click on the refresh button

**Comment by getnot** [comment]
we need to remove 113 also.

**Comment by getnot** [comment]
but let's not do it .. we should have a new joke each time a page refresh or a new tab open

**Comment by nikhil3000** [comment]
the changes in this pr will request for a new joke each time the page is refreshed (hence the call at 113) and it would also request a new joke when the users clicks on the refresh button.

**Pull request closed without merging**
